#!/usr/bin/env sh

limelight -m config width 2
limelight -m config radius 10
limelight -m config placement exterior
limelight -m config active_color 0xFFd9d9d9
limelight -m config normal_color 0x00FFFFFF

echo "limelight configuration loaded.."
